use JewelryShop
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
BEGIN TRAN 
PRINT 'FIRST READ'
SELECT * FROM Bijuterie WHERE id_bij=5
INSERT INTO LogActiuni(nume_tabel,tip_operatie,data) VALUES ('Bijuterie','SELECT',GETDATE())
WAITFOR DELAY '00:00:10' 
PRINT 'SECOND READ'
SELECT * FROM Bijuterie WHERE id_bij=5
INSERT INTO LogActiuni(nume_tabel,tip_operatie,data) VALUES ('Bijuterie','SELECT',GETDATE())
COMMIT TRAN

SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
BEGIN TRAN 
PRINT 'FIRST READ'
SELECT * FROM Bijuterie WHERE id_bij=5
WAITFOR DELAY '00:00:10' 
PRINT 'SECOND READ'
SELECT * FROM Bijuterie WHERE id_bij=5
COMMIT TRAN


/*
se rezolva cu READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
BEGIN TRAN 
PRINT 'FIRST READ'
SELECT * FROM Bijuterie WHERE id_bij=5
WAITFOR DELAY '00:00:10' 
PRINT 'SECOND READ'
SELECT * FROM Bijuterie WHERE id_bij=5
COMMIT TRAN

*/