use JewelryShop
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
BEGIN TRAN 
PRINT 'UPDATE'
UPDATE Bijuterie SET gramaj_bij=10.5 WHERE id_bij=5
INSERT INTO LogActiuni(nume_tabel,tip_operatie,data) VALUES ('Bijuterie','UPDATE',GETDATE())
WAITFOR DELAY '00:00:5' 
PRINT 'CANCEL'
ROLLBACK TRAN

SET TRANSACTION ISOLATION LEVEL READ COMMITTED  
BEGIN TRAN 
PRINT 'UPDATE'
UPDATE Bijuterie SET gramaj_bij=10.5 WHERE id_bij=5
WAITFOR DELAY '00:00:5' 
PRINT 'CANCEL'
ROLLBACK TRAN


/*
se rezolva cu READ COMMITTED 
SET TRANSACTION ISOLATION LEVEL READ COMMITTED  
BEGIN TRAN 
PRINT 'UPDATE'
UPDATE Bijuterie SET gramaj_bij=10.5 WHERE id_bij=5
WAITFOR DELAY '00:00:5' 
PRINT 'CANCEL'
ROLLBACK TRAN
*/