use JewelryShop
GO


SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
PRINT 'INSERT PHANTOM'
WAITFOR DELAY '00:00:05'
INSERT INTO Angajati(nume,post,id_magazin) VALUES('Ioana','m',1)
INSERT INTO LogActiuni(nume_tabel,tip_operatie,data) VALUES ('Angajati','INSERT',GETDATE())
COMMIT

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
PRINT 'INSERT PHANTOM'
WAITFOR DELAY '00:00:05'
INSERT INTO Angajati(nume,post,id_magazin) VALUES('Ioana','m',1)
INSERT INTO LogActiuni(nume_tabel,tip_operatie,data) VALUES ('Angajati','INSERT',GETDATE())
COMMIT

/* se rezolva cu SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
PRINT 'INSERT PHANTOM'
WAITFOR DELAY '00:00:05'
INSERT INTO Angajati(nume,post,id_magazin) VALUES('Ioana','m',1)
INSERT INTO LogActiuni(nume_tabel,tip_operatie,data) VALUES ('Angajati','INSERT',GETDATE())
COMMIT

*/