CREATE DATABASE SEMINAR1
GO
USE SEMINAR1

CREATE DATABASE Seminar1227SGBD2025;
GO
USE Seminar1227SGBD2025;
CREATE TABLE Produse
(cod_p INT PRIMARY KEY IDENTITY,
nume VARCHAR(100),
pret REAL,
producator VARCHAR(100)
);

select * from Produse;